name: ocr-docker
on:
  push:
    paths:
      - 'ocr/ocrserver/**/*'
      - '.github/workflows/ocr-docker.yml'
jobs:
  publish-parcetrace-ocr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the hello-docker Docker image
        run: |
              docker build ./ocr/ocrserver/ --tag ghcr.io/gxjakkap/parcetrace-ocr:latest
              docker push ghcr.io/gxjakkap/parcetrace-ocr:latest